Repository jump-dev/Hypatia.jl, pull requests merged in 2020-10, with the labels that each got.

#593 update compat bounds
  Project.toml
  src/ModelUtilities/ModelUtilities.jl
  src/ModelUtilities/polynomials.jl
Labels: dependencies

#594 relax version bounds for julia and run julia nightly in travis
  .travis.yml
  Project.toml
Labels: dependencies, tests

#595 initialization fixes for wsosl1 cone
  src/Cones/wsosinterpepinormone.jl
Labels: cleanup, dependencies

#596 minor tweaks, add missing inbounds
  src/Cones/epinormspectral.jl
  src/Cones/power.jl
Labels: cleanup

#597 test more real types thru MOI tests
  src/MathOptInterface/cones.jl
  src/MathOptInterface/wrapper.jl
  test/moi.jl
  test/runmoitests.jl
Labels: MOI, tests

#599 remove DynamicPolynomials dependency and lagrange polys from ModelUtilities
  Project.toml
  examples/contraction/JuMP.jl
  examples/polynorm/JuMP.jl
  src/ModelUtilities/ModelUtilities.jl
  src/ModelUtilities/polynomials.jl
  test/modelutilities.jl
  test/runmodelutilitiestests.jl
Labels: cleanup, examples, interface, numerics, tests

#600 fix access for some pointers
  src/Cones/possemideftrisparse.jl
Labels: bug

#601 cleanup stepper and fix corrector bug
  examples/conditionnum/JuMP_test.jl
  examples/densityest/JuMP_test.jl
  examples/densityest/native_test.jl
  examples/expdesign/JuMP_test.jl
  examples/expdesign/native_test.jl
  examples/linearopt/native_test.jl
  examples/matrixcompletion/native.jl
  examples/matrixregression/native.jl
  examples/maxvolume/JuMP_test.jl
  examples/maxvolume/native_test.jl
  examples/muconvexity/JuMP.jl
  examples/muconvexity/JuMP_test.jl
  examples/portfolio/native.jl
  examples/portfolio/native_test.jl
  examples/robustgeomprog/JuMP_test.jl
  examples/shapeconregr/JuMP_test.jl
  examples/sparsepca/native.jl
  examples/sparsepca/native_test.jl
  src/Cones/Cones.jl
  src/Cones/doublynonnegativetri.jl
  src/Cones/epinormeucl.jl
  src/Cones/epinorminf.jl
  src/Cones/epinormspectral.jl
  src/Cones/epipersquare.jl
  src/Cones/episumperentropy.jl
  src/Cones/hypogeomean.jl
  src/Cones/hypoperlog.jl
  src/Cones/hypoperlogdettri.jl
  src/Cones/hypopowermean.jl
  src/Cones/hyporootdettri.jl
  src/Cones/linmatrixineq.jl
  src/Cones/matrixepipersquare.jl
  src/Cones/nonnegative.jl
  src/Cones/possemideftri.jl
  src/Cones/possemideftrisparse.jl
  src/Cones/power.jl
  src/Cones/wsosinterpepinormeucl.jl
  src/Cones/wsosinterpepinormone.jl
  src/Cones/wsosinterpnonnegative.jl
  src/Cones/wsosinterppossemideftri.jl
  src/MathOptInterface/cones.jl
  src/MathOptInterface/wrapper.jl
  src/ModelUtilities/interpolate.jl
  src/Solvers/Solvers.jl
  src/Solvers/process.jl
  src/Solvers/steppers/common.jl
  src/Solvers/steppers/heurcomb.jl
  src/Solvers/systemsolvers/qrchol.jl
  src/linearalgebra/dense.jl
  test/barrier.jl
  test/nativeinstances.jl
  test/nativesets.jl
  test/runbarriertests.jl
  test/runexamplestests.jl
Labels: bug, cleanup, memory, speed

#602 add wsosl1 example and fix bugs in wsos l1 cone
  examples/polynorm/JuMP.jl
  examples/polynorm/JuMP_test.jl
  src/Cones/Cones.jl
  src/Cones/wsosinterpepinormone.jl
  src/Solvers/Solvers.jl
  src/Solvers/systemsolvers/qrchol.jl
  src/linearalgebra/dense.jl
Labels: bug, numerics

#603 more stepper cleanup and options
  examples/runbenchmarks.jl
  src/Solvers/steppers/heurcomb.jl
  src/Solvers/steppers/predorcorr.jl
  test/moi.jl
  test/runmoitests.jl
Labels: cleanup, interface, memory

#604 add inbounds annotations in sparse psd
  src/Cones/possemideftrisparse.jl
Labels: cleanup, speed

#605 make benchmark script work on julia 1.5
  examples/runbenchmarks.jl
  examples/spawn.jl
Labels: benchmarks

#606 improve benchmark sets and script
  examples/nearestpsd/JuMP_benchmark.jl
  examples/polymin/JuMP_benchmark.jl
  examples/runbenchmarks.jl
  examples/shapeconregr/JuMP_benchmark.jl
  examples/spawn.jl
Labels: benchmarks

#607 minor bug fixes and cleanup
  src/Cones/Cones.jl
  src/Cones/doublynonnegativetri.jl
  src/Cones/epinormeucl.jl
  src/Cones/epinorminf.jl
  src/Cones/epinormspectral.jl
  src/Cones/epipersquare.jl
  src/Cones/episumperentropy.jl
  src/Cones/hypogeomean.jl
  src/Cones/hypoperlog.jl
  src/Cones/hypoperlogdettri.jl
  src/Cones/hypopowermean.jl
  src/Cones/hyporootdettri.jl
  src/Cones/linmatrixineq.jl
  src/Cones/matrixepipersquare.jl
  src/Cones/nonnegative.jl
  src/Cones/possemideftri.jl
  src/Cones/possemideftrisparse.jl
  src/Cones/power.jl
  src/Cones/wsosinterpepinormeucl.jl
  src/Cones/wsosinterpepinormone.jl
  src/Cones/wsosinterpnonnegative.jl
  src/Cones/wsosinterppossemideftri.jl
  src/Solvers/Solvers.jl
  src/Solvers/linesearch.jl
  src/Solvers/process.jl
  src/Solvers/steppers/heurcomb.jl
Labels: bug, cleanup

#608 change JuMP portfolio example to rebalancing
  examples/portfolio/JuMP.jl
  examples/portfolio/JuMP_test.jl
Labels: benchmarks, examples

#610 update definitions of violations in processing of examples
  examples/common.jl
  examples/common_JuMP.jl
  examples/common_native.jl
  examples/runbenchmarks.jl
  test/runcblibtests.jl
  test/runexamplestests.jl
Labels: benchmarks, examples, tests

#611 fix some benchmark script failures
  examples/runbenchmarks.jl
  examples/spawn.jl
Labels: benchmarks

#612 use new convergence conditions
  examples/runbenchmarks.jl
  src/Cones/wsosinterpepinormone.jl
  src/Solvers/Solvers.jl
  src/Solvers/steppers/heurcomb.jl
  src/Solvers/steppers/predorcorr.jl
  test/runcblibtests.jl
  test/runmoitests.jl
  test/runnativetests.jl
Labels: interface, speculative

#614 improve benchmark script; use more views etc to improve efficiency
  examples/common.jl
  examples/common_JuMP.jl
  examples/runbenchmarks.jl
  examples/spawn.jl
  src/Cones/Cones.jl
  src/Cones/doublynonnegativetri.jl
  src/Cones/epinormeucl.jl
  src/Cones/epinorminf.jl
  src/Cones/epipersquare.jl
  src/Cones/episumperentropy.jl
  src/Cones/hypogeomean.jl
  src/Cones/hypoperlog.jl
  src/Cones/hypopowermean.jl
  src/Cones/hyporootdettri.jl
  src/Cones/matrixepipersquare.jl
  src/Cones/possemideftrisparse.jl
  src/Cones/power.jl
  src/Cones/wsosinterpepinormeucl.jl
  src/Cones/wsosinterpepinormone.jl
  src/Cones/wsosinterppossemideftri.jl
  src/ModelUtilities/ModelUtilities.jl
  src/ModelUtilities/interpolate.jl
  src/Solvers/Solvers.jl
  src/Solvers/process.jl
  src/Solvers/systemsolvers/common.jl
  src/Solvers/systemsolvers/naive.jl
  src/Solvers/systemsolvers/naiveelim.jl
  src/Solvers/systemsolvers/symindef.jl
Labels: benchmarks, memory, speed

#616 refactor and simplify arrow hessian oracles
  examples/portfolio/JuMP_test.jl
  src/Cones/Cones.jl
  src/Cones/doublynonnegativetri.jl
  src/Cones/epinorminf.jl
  src/Cones/epinormspectral.jl
  src/Cones/episumperentropy.jl
  src/Cones/hypogeomean.jl
  src/Cones/hypoperlog.jl
  src/Cones/hypoperlogdettri.jl
  src/Cones/hypopowermean.jl
  src/Cones/hyporootdettri.jl
  src/Cones/linmatrixineq.jl
  src/Cones/matrixepipersquare.jl
  src/Cones/power.jl
  src/Cones/wsosinterpepinormeucl.jl
  src/Cones/wsosinterpepinormone.jl
  src/Cones/wsosinterpnonnegative.jl
  src/Cones/wsosinterppossemideftri.jl
  src/ModelUtilities/interpolate.jl
  src/Solvers/process.jl
  src/Solvers/systemsolvers/common.jl
  test/nativesets.jl
  test/runexamplestests.jl
  test/runnativetests.jl
Labels: cleanup, memory, numerics

#615 WIP: add lower complexity oracles for more complicated WSOS cones
  src/Cones/wsosinterpepinormeucl.jl
  src/Cones/wsosinterppossemideftri.jl
Labels: numerics, speed
