Repository jump-dev/Hypatia.jl, pull requests merged in 2021-04, with the labels that each got.

#667 WIP: fix some slow oracles and failing instances
  examples/matrixcompletion/JuMP.jl
  examples/matrixcompletion/native.jl
  src/Cones/Cones.jl
  src/Cones/epinorminf.jl
  src/Cones/epiperentropy.jl
  src/Cones/epirelentropy.jl
  src/MathOptInterface/cones.jl
  src/Solvers/search.jl
  test/cone.jl
  test/nativeinstances.jl
  test/runconetests.jl
  test/runexamplestests.jl
  test/runmoitests.jl
  test/runtests.jl
Labels: benchmarks, cleanup, interface, memory, numerics, speed, tests

#662 get a better LMI TOA
  src/Cones/linmatrixineq.jl
Labels: numerics, speed

#668 make stepper analysis script produce more CSVs
  benchmarks/stepper/analyze.jl
  examples/matrixcompletion/JuMP_test.jl
  examples/matrixcompletion/native_test.jl
Labels: benchmarks

#669 make more tweaks to benchmark analysis scripts
  benchmarks/natvsext/analyze.jl
  benchmarks/stepper/analyze.jl
Labels: benchmarks, cleanup

#670 improve scalar wsos oracles and test complex case
  examples/polymin/data.jl
  src/Cones/wsosinterpnonnegative.jl
  src/ModelUtilities/ModelUtilities.jl
  src/ModelUtilities/complex.jl
  src/ModelUtilities/interpolate.jl
  test/cone.jl
  test/nativeinstances.jl
  test/nativesets.jl
  test/runconetests.jl
Labels: interface, memory, numerics, speed, tests

#671 improve LMI cone oracles
  examples/conditionnum/JuMP.jl
  examples/conditionnum/JuMP_test.jl
  src/Cones/linmatrixineq.jl
  test/nativeinstances.jl
  test/runexamplestests.jl
Labels: memory, numerics, speed

#672 improve wsosmat corrector slightly
  src/Cones/wsosinterpnonnegative.jl
  src/Cones/wsosinterppossemideftri.jl
Labels: speed

#673 reduce time complexity in the TOO of WSOS L2 cone
  src/Cones/wsosinterpepinormeucl.jl
  src/Cones/wsosinterpnonnegative.jl
Labels: speed

#674 WIP: use expensive hess prods, only use iterative refinement when needed
  examples/conditionnum/JuMP_test.jl
  examples/contraction/JuMP_test.jl
  examples/nearestpolymat/JuMP_test.jl
  examples/semidefinitepoly/JuMP_test.jl
  src/Cones/linmatrixineq.jl
  src/Cones/wsosinterpnonnegative.jl
  src/Cones/wsosinterppossemideftri.jl
  src/Solvers/Solvers.jl
  src/Solvers/steppers/combined.jl
  src/Solvers/steppers/predorcent.jl
  src/Solvers/systemsolvers/common.jl
  test/nativesets.jl
  test/runconetests.jl
  test/runexamplestests.jl
  test/runmoitests.jl
  test/runnativetests.jl
  test/runtests.jl
Labels: interface, numerics, speed

#675 record example type in dataframe
  benchmarks/natvsext/run.jl
  benchmarks/setup.jl
  benchmarks/stepper/run.jl
  test/runexamplestests.jl
Labels: benchmarks

#676 improve wsos oracles speed
  src/Cones/Cones.jl
  src/Cones/wsosinterpnonnegative.jl
Labels: speed

#677 improve time complexity for WSOS L1 TOO
  src/Cones/wsosinterpepinormone.jl
Labels: speed

#678 use expensive hessian products only when needed
  src/Cones/Cones.jl
  src/Cones/doublynonnegativetri.jl
  src/Cones/epinormeucl.jl
  src/Cones/epinorminf.jl
  src/Cones/epinormspectral.jl
  src/Cones/epiperentropy.jl
  src/Cones/epipersquare.jl
  src/Cones/epipertraceentropytri.jl
  src/Cones/epirelentropy.jl
  src/Cones/epitracerelentropytri.jl
  src/Cones/generalizedpower.jl
  src/Cones/hypogeomean.jl
  src/Cones/hypoperlog.jl
  src/Cones/hypoperlogdettri.jl
  src/Cones/hypopowermean.jl
  src/Cones/hyporootdettri.jl
  src/Cones/linmatrixineq.jl
  src/Cones/matrixepipersquare.jl
  src/Cones/nonnegative.jl
  src/Cones/possemideftri.jl
  src/Cones/possemideftrisparse.jl
  src/Cones/wsosinterpepinormeucl.jl
  src/Cones/wsosinterpepinormone.jl
  src/Cones/wsosinterpnonnegative.jl
  src/Cones/wsosinterppossemideftri.jl
  src/Solvers/steppers/common.jl
  src/Solvers/systemsolvers/common.jl
  src/Solvers/systemsolvers/qrchol.jl
  test/cone.jl
Labels: cleanup, numerics, speed

#679 count number of instances with loosened tolerances
  benchmarks/stepper/analyze.jl
Labels: benchmarks

#681 remove unneeded preallocated space in matrix wsos
  src/Cones/wsosinterppossemideftri.jl
Labels: memory

#680 rename shift to back
  benchmarks/stepper/analyze.jl
  benchmarks/stepper/run.jl
Labels: benchmarks

#682 refactor hess prod and correction for wsosmat
  src/Cones/wsosinterpnonnegative.jl
  src/Cones/wsosinterppossemideftri.jl
Labels: cleanup, speed

#683 WIP: add different implementation types for sparse PSD cone, add new example
  benchmarks/stepper/run.jl
  examples/nearestpsd/JuMP.jl
  examples/nearestpsd/JuMP_benchmark.jl
  examples/nearestpsd/JuMP_test.jl
  examples/sparselmi/JuMP.jl
  examples/sparselmi/JuMP_test.jl
  src/Cones/Cones.jl
  src/Cones/possemideftrisparse/cholmodimpl.jl
  src/Cones/possemideftrisparse/denseimpl.jl
  src/Cones/possemideftrisparse/possemideftrisparse.jl
  src/MathOptInterface/cones.jl
  test/cone.jl
  test/moicones.jl
  test/nativeinstances.jl
  test/runconetests.jl
  test/runexamplestests.jl
  test/runmoitests.jl
Labels: cleanup, examples, interface, tests

#685 delete unused import
  test/cone.jl
Labels: cleanup, tests

#684 WIP: add new generic matrix monotone epigraph cone
  Project.toml
  examples/lotkavolterra/JuMP.jl
  src/Cones/Cones.jl
  src/Cones/doublynonnegativetri.jl
  src/Cones/epinormeucl.jl
  src/Cones/epinorminf.jl
  src/Cones/epinormspectral.jl
  src/Cones/epiperentropy.jl
  src/Cones/epipersepspectral/epipersepspectral.jl
  src/Cones/epipersepspectral/matrixcsqr.jl
  src/Cones/epipersepspectral/sepspectralfun.jl
  src/Cones/epipersepspectral/vectorcsqr.jl
  src/Cones/epipersquare.jl
  src/Cones/epipertraceentropytri.jl
  src/Cones/epirelentropy.jl
  src/Cones/epitrrelentropytri.jl
  src/Cones/generalizedpower.jl
  src/Cones/hypogeomean.jl
  src/Cones/hypoperlog.jl
  src/Cones/hypoperlogdettri.jl
  src/Cones/hypopowermean.jl
  src/Cones/hyporootdettri.jl
  src/Cones/linmatrixineq.jl
  src/Cones/matrixepipersquare.jl
  src/Cones/nonnegative.jl
  src/Cones/possemideftri.jl
  src/Cones/possemideftrisparse/cholmodimpl.jl
  src/Cones/possemideftrisparse/denseimpl.jl
  src/Cones/possemideftrisparse/possemideftrisparse.jl
  src/Cones/wsosinterpepinormeucl.jl
  src/Cones/wsosinterpepinormone.jl
  src/Cones/wsosinterpnonnegative.jl
  src/Cones/wsosinterppossemideftri.jl
  src/MathOptInterface/cones.jl
  src/ModelUtilities/domains.jl
  src/ModelUtilities/interpolate.jl
  test/cone.jl
  test/moicones.jl
  test/nativeinstances.jl
  test/nativesets.jl
  test/runconetests.jl
Labels: interface, tests
