Repository jump-dev/Hypatia.jl, pull requests merged in 2021-03, with the labels that each got.

#652 time factorizations and system solver setup
  src/Solvers/Solvers.jl
  src/Solvers/steppers/combined.jl
  src/Solvers/steppers/predorcent.jl
  src/Solvers/systemsolvers/naive.jl
  src/Solvers/systemsolvers/naiveelim.jl
  src/Solvers/systemsolvers/qrchol.jl
  src/Solvers/systemsolvers/symindef.jl
Labels: benchmarks, interface, speed

#653 remove constant multiplier from rootdet barrier
  src/Cones/hyporootdettri.jl
  test/barrier.jl
Labels: numerics, speed

#655 rename randompolymat to nearestpolymat
  examples/nearestpolymat/JuMP.jl
  examples/nearestpolymat/JuMP_benchmark.jl
  examples/nearestpolymat/JuMP_test.jl
  examples/processbenchmarks.jl
  examples/runbenchmarks.jl
  test/runexamplestests.jl
Labels: cleanup, examples

#656 refactor wsos matrix oracles for faster grad
  src/Cones/wsosinterppossemideftri.jl
Labels: speed

#657 refactor wsos L1 cone, making grad faster
  src/Cones/wsosinterpepinormone.jl
  src/Cones/wsosinterppossemideftri.jl
Labels: speed

#658 refactor wsos L2 cone, making grad faster
  src/Cones/wsosinterpepinormeucl.jl
Labels: speed

#659 add scripts for benchmarking steppers
  .gitignore
  benchmarks/natvsext/README.md
  benchmarks/natvsext/analyze.jl
  benchmarks/natvsext/run.jl
  benchmarks/setup.jl
  benchmarks/spawn.jl
  benchmarks/stepper/README.md
  benchmarks/stepper/analyze.jl
  benchmarks/stepper/run.jl
  examples/CBLIB/JuMP.jl
  examples/CBLIB/JuMP_test.jl
  examples/CBLIB/cblib_data/expdesign_D_8_4.cbf.gz
  examples/common.jl
  examples/common_JuMP.jl
  examples/common_native.jl
  examples/matrixregression/native.jl
  examples/polymin/native.jl
  examples/sparsepca/native.jl
  src/Solvers/Solvers.jl
  test/cblibsets.jl
  test/runcblibtests.jl
  test/runexamplestests.jl
  test/runtests.jl
Labels: benchmarks, tests

#661 add various example instances to benchmark
  benchmarks/stepper/run.jl
  examples/centralpolymat/JuMP_test.jl
  examples/conditionnum/JuMP_test.jl
  examples/contraction/JuMP_test.jl
  examples/densityest/JuMP_test.jl
  examples/envelope/JuMP_test.jl
  examples/expdesign/JuMP_test.jl
  examples/linearopt/native_test.jl
  examples/lotkavolterra/JuMP_test.jl
  examples/lyapunovstability/JuMP_test.jl
  examples/matrixcompletion/JuMP_test.jl
  examples/matrixquadratic/JuMP_test.jl
  examples/matrixregression/JuMP_test.jl
  examples/maxvolume/JuMP.jl
  examples/maxvolume/JuMP_test.jl
  examples/muconvexity/JuMP_test.jl
  examples/nearestpolymat/JuMP_test.jl
  examples/nearestpsd/JuMP_test.jl
  examples/normconepoly/JuMP.jl
  examples/normconepoly/JuMP_test.jl
  examples/polymin/JuMP_test.jl
  examples/polynorm/JuMP_test.jl
  examples/portfolio/JuMP_test.jl
  examples/regionofattr/JuMP_test.jl
  examples/robustgeomprog/JuMP_test.jl
  examples/secondorderpoly/JuMP_test.jl
  examples/semidefinitepoly/JuMP_test.jl
  examples/shapeconregr/JuMP_test.jl
  examples/signomialmin/JuMP_test.jl
  examples/sparsepca/native.jl
  examples/sparsepca/native_test.jl
  examples/stabilitynumber/JuMP_test.jl
  test/runexamplestests.jl
Labels: benchmarks, examples, tests

#663 faster TOA for wsos nonnegative
  src/Cones/wsosinterpnonnegative.jl
Labels: speed

#665 add power benchmark instances and tweaks in stepper run script
  benchmarks/stepper/run.jl
  examples/matrixcompletion/native_test.jl
  examples/maxvolume/native_test.jl
Labels: benchmarks, examples

#666 speed up matrix wsos TOA
  examples/densityest/native_test.jl
  src/Cones/wsosinterpnonnegative.jl
  src/Cones/wsosinterppossemideftri.jl
Labels: speed

#664 cleanup cone oracle tests, check oracle allocations
  Project.toml
  examples/common_JuMP.jl
  examples/matrixcompletion/native.jl
  examples/maxvolume/native.jl
  src/Cones/Cones.jl
  src/Cones/generalizedpower.jl
  src/MathOptInterface/cones.jl
  test/barrier.jl
  test/cone.jl
  test/moi.jl
  test/moicones.jl
  test/nativeinstances.jl
  test/nativesets.jl
  test/runbarriertests.jl
  test/runconetests.jl
  test/runtests.jl
Labels: cleanup, memory, numerics, tests
