Repository jump-dev/Hypatia.jl, pull requests merged in 2021-01, with the labels that each got.

#637 cleanup and add barrier oracles numerics checks
  .travis.yml
  examples/conditionnum/JuMP_test.jl
  examples/lotkavolterra/JuMP.jl
  examples/lotkavolterra/JuMP_test.jl
  examples/lyapunovstability/JuMP_test.jl
  examples/polynorm/JuMP_test.jl
  src/Cones/Cones.jl
  src/Cones/epinorminf.jl
  src/Cones/epirelentropy.jl
  src/Cones/epitracerelentropytri.jl
  src/Solvers/Solvers.jl
  src/Solvers/steppers/combined.jl
  src/Solvers/steppers/common.jl
  src/Solvers/steppers/predorcent.jl
  src/Solvers/systemsolvers/common.jl
  src/Solvers/systemsolvers/qrchol.jl
  src/linearalgebra/dense.jl
  test/nativeinstances.jl
  test/nativesets.jl
  test/runmoitests.jl
  test/runnativetests.jl
Labels: numerics

#638 cleanup and improve slow progress checks
  examples/polymin/JuMP_test.jl
  src/Cones/Cones.jl
  src/Cones/epirelentropy.jl
  src/Solvers/Solvers.jl
  src/Solvers/steppers/combined.jl
  src/Solvers/steppers/common.jl
Labels: cleanup, interface, numerics

#634 add more entropy-like cones
  src/Cones/Cones.jl
  src/Cones/epiperentropy.jl
  src/Cones/epipertraceentropytri.jl
  src/Cones/epitracerelentropytri.jl
  src/MathOptInterface/cones.jl
  test/barrier.jl
  test/moicones.jl
  test/nativeinstances.jl
  test/nativesets.jl
  test/runbarriertests.jl
Labels: interface

#639 add third order derivatives for relative entropy
  src/Cones/Cones.jl
  src/Cones/epipertraceentropytri.jl
  src/Cones/epitracerelentropytri.jl
Labels: numerics, speed

#641 add and test stepper options and cleanup search
  src/Solvers/Solvers.jl
  src/Solvers/search.jl
  src/Solvers/steppers/combined.jl
  src/Solvers/steppers/predorcent.jl
  test/runnativetests.jl
Labels: cleanup, interface, tests
