Repository jump-dev/Hypatia.jl, pull requests merged in 2021-02, with the labels that each got.

#642 if not spawning in runbenchmarks, run compile instance
  examples/runbenchmarks.jl
Labels: benchmarks

#643 simplify steppers and alpha search, add optional initial alpha heuristic
  examples/densityest/JuMP_test.jl
  src/Solvers/search.jl
  src/Solvers/steppers/combined.jl
  src/Solvers/steppers/predorcent.jl
  test/runmoitests.jl
Labels: cleanup, interface, speed

#646 delete a redundant line of code
  src/Cones/hyporootdettri.jl
Labels: cleanup

#647 improve predorcent stepper
  src/Cones/Cones.jl
  src/Solvers/steppers/predorcent.jl
Labels: bug, cleanup

#648 correct MOI.Silent
  src/MathOptInterface/wrapper.jl
Labels: MOI, bug

#649 add timings for subprocedures
  src/Solvers/Solvers.jl
  src/Solvers/steppers/combined.jl
  src/Solvers/steppers/predorcent.jl
Labels: interface

#650 use lower bound on hessian nbhd to speed up search
  src/Solvers/search.jl
Labels: speed
